keys:
  - &admin_atp age1gym933jnyln9nud8vhg44vtp983prgfpnlxr0zw2tr9x9s575vyqyufmyd
  - &server_ammonite age1luz57tez0kjk5njt3xpep25cvnlva2z9dqeca3df733mxdhhwvdsz06yf4
  - &server_auction age1ccwqnh66ktsccup8urtmdwqku3wc37s754j3l7k9vqagp6ll3veqhwjhxl
  - &server_edward age1mvka0nrqwvfuk4mpmw05htyacw3nhmxv4rdhv9ay6t78gnd44arqq7trx6
  - &server_crystal age1vacywlqvmx6d2tfshssjky3k8zeg0z80jeja44mepq0vtuderdjq4sl78v
  - &server_freezer age1c5pu3h32u47c7k3g6xhqexsu3wyuj68us0cktgy78v0luyxxx5xqed37zk
  - &server_homelab age1y3fpqvn85xagmg0c8nzefum7g6g27vzul6gk66474xmdy62j5ycq5ezaa2
  - &server_icecream age1y5my805jn6krn28krxufsf7t5tg5ce7d78dy7c70cu5emc64ep5sfenyhr
  - &server_octopus age17dsxdapjtfed2u9mgf9vx4pk4emwt7dg7h6298n7xu4mz3fhkflsg6jecw
  - &server_squid age16rgr0awelazlgze3gn56r3a4al7vja70tyk86navwvzmykn3d4eqf29adn
  - &server_cthulhu age1g007d9q5j2gupvav8yfk98zwp46swqgxsrgp4s3g5dj78n6cn3gs6vu0nm
  - &server_nautilus age1g54wdqkq50tqmwmgstss0tag4wzx0g8z4aywx3646hj8aujee34q0020zr
creation_rules:
  - path_regex: machines/ammonite/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/ammonite/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_ammonite

  - path_regex: machines/auction/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/auction/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_auction

  - path_regex: machines/edward/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/edward/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_edward

  - path_regex: machines/crystal/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/crystal/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_crystal

  - path_regex: machines/freezer/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/freezer/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_freezer

  - path_regex: machines/homelab/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/homelab/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_homelab

  - path_regex: machines/icecream/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/icecream/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_icecream

  - path_regex: machines/octopus/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/octopus/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_octopus

  - path_regex: machines/squid/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/squid/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_squid

  - path_regex: machines/cthulhu/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/cthulhu/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_cthulhu

  - path_regex: machines/nautilus/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/nautilus/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_nautilus
