keys:
  - &admin_atp age1gym933jnyln9nud8vhg44vtp983prgfpnlxr0zw2tr9x9s575vyqyufmyd
  - &server_auction age1ccwqnh66ktsccup8urtmdwqku3wc37s754j3l7k9vqagp6ll3veqhwjhxl
  - &server_icecream age1uxu7lwlge36s6vrep05jq23kt44ftvxmg3j5ymtdkje9llte7elq7tejwh
  - &server_homelab age1y3fpqvn85xagmg0c8nzefum7g6g27vzul6gk66474xmdy62j5ycq5ezaa2
creation_rules:
  - path_regex: machines/auction/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/auction/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_auction

  - path_regex: machines/icecream/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/icecream/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_icecream

  - path_regex: machines/homelab/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/homelab/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_homelab
