keys:
  - &admin_atp age1gym933jnyln9nud8vhg44vtp983prgfpnlxr0zw2tr9x9s575vyqyufmyd
  - &server_auction age1ccwqnh66ktsccup8urtmdwqku3wc37s754j3l7k9vqagp6ll3veqhwjhxl
  - &server_crystal age1vacywlqvmx6d2tfshssjky3k8zeg0z80jeja44mepq0vtuderdjq4sl78v
  - &server_freezer age1c5pu3h32u47c7k3g6xhqexsu3wyuj68us0cktgy78v0luyxxx5xqed37zk
  - &server_homelab age1y3fpqvn85xagmg0c8nzefum7g6g27vzul6gk66474xmdy62j5ycq5ezaa2
  - &server_icecream age1uxu7lwlge36s6vrep05jq23kt44ftvxmg3j5ymtdkje9llte7elq7tejwh
  - &server_octopus age1uuym8hf6d2zypn6pfylv7klhau58s0uf5nk70yggeuefqa6yx9ls2puppv
  - &server_squid age1gwwmvkehwjlkky62smvvkpa6y33f3akcj28dl7tur8nyc3vra9astzjcau
creation_rules:
  - path_regex: machines/auction/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/auction/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_auction

  - path_regex: machines/crystal/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/crystal/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_crystal

  - path_regex: machines/freezer/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/freezer/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_freezer

  - path_regex: machines/homelab/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/homelab/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_homelab

  - path_regex: machines/icecream/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/icecream/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_icecream

  - path_regex: machines/octopus/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/octopus/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_octopus

  - path_regex: machines/squid/values/*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/squid/secrets/*
    key_groups:
      - age:
          - *admin_atp
          - *server_squid
