keys:
  - &admin_atp age1gym933jnyln9nud8vhg44vtp983prgfpnlxr0zw2tr9x9s575vyqyufmyd
  - &server_auction age1ccwqnh66ktsccup8urtmdwqku3wc37s754j3l7k9vqagp6ll3veqhwjhxl
  - &server_crystal age1vacywlqvmx6d2tfshssjky3k8zeg0z80jeja44mepq0vtuderdjq4sl78v
  - &server_freezer age1c5pu3h32u47c7k3g6xhqexsu3wyuj68us0cktgy78v0luyxxx5xqed37zk
  - &server_homelab age1y3fpqvn85xagmg0c8nzefum7g6g27vzul6gk66474xmdy62j5ycq5ezaa2
  - &server_icecream age1uxu7lwlge36s6vrep05jq23kt44ftvxmg3j5ymtdkje9llte7elq7tejwh
  - &server_octopus age1w9nd8s78k0gfzjdqe53dgvqpuey84qthphur3nj5hre9dg0h2cpsdlv73m
  - &server_squid age19nnysn8lz8sdvd0ujak5gm6xlgr539mh32753v8ku50ma4nff4nqwjj5tm
  - &server_cthulhu age1g007d9q5j2gupvav8yfk98zwp46swqgxsrgp4s3g5dj78n6cn3gs6vu0nm
  - &server_nautilus age1tl7qz9vum9m9a8sz6flumhrt3luwzshpnsaalyl68w6mn8j8ngjs92tfe9
creation_rules:
  - path_regex: machines/auction/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/auction/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_auction

  - path_regex: machines/crystal/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/crystal/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_crystal

  - path_regex: machines/freezer/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/freezer/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_freezer

  - path_regex: machines/homelab/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/homelab/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_homelab

  - path_regex: machines/icecream/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/icecream/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_icecream

  - path_regex: machines/octopus/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/octopus/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_octopus

  - path_regex: machines/squid/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/squid/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_squid

  - path_regex: machines/cthulhu/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/cthulhu/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_cthulhu

  - path_regex: machines/nautilus/values/.*
    key_groups:
      - age:
          - *admin_atp
  - path_regex: machines/nautilus/secrets/.*
    key_groups:
      - age:
          - *admin_atp
          - *server_nautilus
